import type { Quiz } from '@/types';

export const mockQuizzes: Quiz[] = [
  {
    id: 'q1',
    subject: 'Math',
    topic: 'Algebra',
    type: 'mcq',
    question: 'What is the value of x in the equation 2x + 5 = 15?',
    options: ['x = 3', 'x = 5', 'x = 7', 'x = 10'],
    correctAnswer: 'x = 5',
    explanation: 'Subtract 5 from both sides: 2x = 10, then divide by 2: x = 5',
    difficulty: 'easy',
  },
  {
    id: 'q2',
    subject: 'Science',
    topic: 'Physics',
    type: 'mcq',
    question: 'What is the SI unit of force?',
    options: ['Newton', 'Joule', 'Watt', 'Pascal'],
    correctAnswer: 'Newton',
    explanation: 'The SI unit of force is the Newton, named after Sir Isaac Newton.',
    difficulty: 'easy',
  },
  {
    id: 'q3',
    subject: 'English',
    topic: 'Grammar',
    type: 'fill-blanks',
    question: 'Fill in the blank: She ___ to school every day.',
    options: ['go', 'goes', 'going', 'went'],
    correctAnswer: 'goes',
    explanation: 'For third person singular (she/he/it), we add -es to the verb.',
    difficulty: 'easy',
  },
  {
    id: 'q4',
    subject: 'Math',
    topic: 'Geometry',
    type: 'true-false',
    question: 'A triangle has 4 sides.',
    options: ['True', 'False'],
    correctAnswer: 'False',
    explanation: 'A triangle has 3 sides, not 4.',
    difficulty: 'easy',
  },
  {
    id: 'q5',
    subject: 'Science',
    topic: 'Chemistry',
    type: 'mcq',
    question: 'What is the chemical symbol for water?',
    options: ['H2O', 'CO2', 'NaCl', 'O2'],
    correctAnswer: 'H2O',
    explanation: 'Water is composed of two hydrogen atoms and one oxygen atom.',
    difficulty: 'easy',
  },
  {
    id: 'q6',
    subject: 'English',
    topic: 'Vocabulary',
    type: 'mcq',
    question: 'What does "benevolent" mean?',
    options: ['Kind and generous', 'Angry and hostile', 'Quick and agile', 'Quiet and shy'],
    correctAnswer: 'Kind and generous',
    explanation: 'Benevolent means well-meaning, kind, and generous.',
    difficulty: 'medium',
  },
  {
    id: 'q7',
    subject: 'Math',
    topic: 'Arithmetic',
    type: 'scenario',
    question: 'Rahul has 24 apples. He gives 1/4 of them to his friend. How many apples does he have left?',
    options: ['6', '12', '18', '20'],
    correctAnswer: '18',
    explanation: '1/4 of 24 = 6 apples given away. 24 - 6 = 18 apples remaining.',
    difficulty: 'medium',
  },
  {
    id: 'q8',
    subject: 'Science',
    topic: 'Biology',
    type: 'true-false',
    question: 'The human heart has 4 chambers.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'The human heart has four chambers: two atria and two ventricles.',
    difficulty: 'medium',
  },
];
